### PR TITLE
add timestamps to vote model

### PR DESCRIPTION
**Pull request by vardyb**
Added timestamp fields to `vote` model so we can track multiple votes from same user if they change their mind.

Implemented for #88

### CODE REVIEW

**Comment by tansaku** [comment]
@vardyb thanks for this - do we also need to adjust where this gets passed in via the controller, or will it get filled in automatically by mongoose?

**Comment by tansaku** [comment]
and do any tests need adjusting?

**Comment by vardyb** [comment]
@tansaku   yes the timestamp fields get automatically added by mongoose so no need to make any further changes to the controller.  Because this is functionality of another module and not handled by our code I didn't feel any changes to the tests were necessary?

**Comment by tansaku** [comment]
@vardyb oh that sounds great :-) no, no extra tests needed here if the existing ones are passing ...

**Pull request merged**
